<?php

namespace App;



class Action extends Base
{
    protected $table = 'actions';
    protected $fillable = ['title','content','public','period','sort'];
    public $timestamps = false;

    public function pictures(){
        return $this->hasMany('App\Pictures','note_id')->where('link','=','action')->orderby('sort');
    }

    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {

        $this->pictures->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
