<?php

namespace App;
use Log;

class Blog extends Base
{
    protected $table = 'blogs';
    protected $fillable = ['url','link','title','content','seo_description','seo_keywords','seo_title','sort','seo_content','date','blog_id','small_content','public'];

    protected $dates = [
        'created_at',
        'updated_at',
        'date'
    ];

    public function getRouteKeyName()
    {
        return 'url';
    }

    public function gallery(){
        return $this->hasMany('App\Pictures','note_id')->where('link','=','blog')->orderBy('sort');
    }

    public function setLinkAttribute($value){
        $this->attributes['link'] = empty($value)?str_slug($this->title):$value;
        $this->updateUrl();
    }

    public function updateUrl(){
        $parent=$this->parent;
        $this->url = isset($parent->url)?$parent->url.'/'.$this->link:$this->link;
    }

    public function setUrlChilds(){
        foreach($this->childs as $child){
            $child->updateUrl();
            $child->save();
        }
    }

    public function url(){
        return '/'.$this->url;
    }

    public function parent(){
        return $this->hasOne('App\Blog','id','blog_id');
    }

    public function childs(){
        return $this->hasMany('App\Blog')->orderBy('date','desc');
    }

    public function bread($parent_url=''){
        $bread = [['link'=>$parent_url.$this->url(), 'title'=>$this->title]];
        if($this->blog_id!=0){
           /* if($this->parent->childs->first()->id==$this->id&&$this->parent->page_id==0){ // если это первый потомок корневого елемента то ссылка как у родителя
                $bread = $this->parent->bread();
            }else{*/
                $bread = array_merge($this->parent->bread($parent_url),$bread);
//            }
        }
        return $bread;
    }

//    public function save(){
//        $res = parent::save();
//        $this->setUrlChilds();
//        return $res;
//    }

    public static function boot()
    {
        parent::boot();

        static::saved(function($page)
        {
            $page->setUrlChilds();

        });

    }

    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {

        $this->gallery->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
