<?php

namespace App;



class Disease extends Base
{
    protected $table = 'diseases';
    protected $fillable = ['title','sort'];
    public $timestamps = false;

    public function services(){
        return $this->belongsToMany('App\Service');
    }
    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
