<?php

namespace App;

class DopService extends Base
{
    protected $table = 'dop_services';
    protected $fillable = ['title','content','price','price_max'];
    public $timestamps = false;

    public function services(){
        return $this->belongsToMany('App\Service');
    }
    
    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
