<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Base
{
    protected $table = 'news';
    protected $fillable = ['title','content','date','public','action'];
    protected $dates = ['date'];
    public $timestamps = false;

    public function pictures(){
        return $this->hasMany('App\Pictures','note_id')->where('link','=','news')->orderby('sort');
    }

    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {

        $this->pictures->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
