<?php

namespace App;

class Price extends Base
{
    protected $table = 'prices';
    protected $fillable = ['title','content','price','price_max','sort'];
    public $timestamps = false;

    public function service(){
        return $this->hasOne('App\Service');
    }
    
    /**
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
